### ISSUE TITLE
Undefined function

### ISSUE THREAD

**Issue by zhouyi0812** [FeeLab/seqNMF#6]
Hello! 

I was trying to run your code on Matlab, and found it was an error like this:

Error in untitled (line 18)
X = generate_data(T,Nneurons,Dt,NeuronNoise,SeqNoiseTime,SeqNoiseNeuron,0,0,0,0,0);

Undefined function 'generate_data' for input arguments of type 'double'.

I wonder should I write a function myself or import any toolbox? Sorry I used to use python and not sure about matlab.

Thank you! 

I tried to use the generate_data.m but it says not enough data 

Not enough input arguments.

Error in generate_data (line 3)
if seed == 0

**Comment by emackev** [comment]
Hi, sorry just seeing this now -- please make sure that the seqNMF folder is added to your MATLAB path (in the home tab, there's a set path button).

**Comment by emackev** [comment]
Hi, sorry just seeing this now -- please make sure that the seqNMF folder is added to your MATLAB path (in the home tab, there's a set path button).
